//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuestionnaireDBEntities : DbContext
    {
        public QuestionnaireDBEntities()
            : base("name=QuestionnaireDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AdminInfo> AdminInfo { get; set; }
        public DbSet<CommentInfo> CommentInfo { get; set; }
        public DbSet<LaudInfo> LaudInfo { get; set; }
        public DbSet<OptionInfo> OptionInfo { get; set; }
        public DbSet<PapersInfo> PapersInfo { get; set; }
        public DbSet<SubjectInfo> SubjectInfo { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
        public DbSet<VoteInfo> VoteInfo { get; set; }
    }
}
