//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionInfo
    {
        public string OptionId { get; set; }
        public string OptionContent { get; set; }
        public Nullable<int> SubjectId { get; set; }
        public Nullable<System.DateTime> OptionDate { get; set; }
        public string AdminId { get; set; }
    }
}
