//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFClassLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubjectInfo
    {
        public int SubjectId { get; set; }
        public string SubjectDepict { get; set; }
        public Nullable<int> PapersId { get; set; }
        public Nullable<int> SubjectType { get; set; }
        public Nullable<System.DateTime> SubjectDate { get; set; }
        public string AdminId { get; set; }
    }
}
